language: node_js
node_js: node
deploy:
  provider: heroku
  api_key: f2fe1f20-1ab4-4dbf-a32b-8aecb13d04ce
  app: obscure-mountain-57946
  on:
    repo: luigomez11/node-shopping-list-integration-tests
