language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: cWJs3vWCaKDX76H3SsM2PLsGmDugk5/0TYtcuajcgAnSABIDkD3rzcUA+XrHgAC10c7MTTRT6LMK487OtbDkK1g5rcXRS9XA3S839C7mvyfPs1jXqrVoDu6/3bt7jC8RX+6PvmZPW/U4Fm6bG7obays0Cv7A/Z5zHgNGRg+O3OauybzoIAy1aN6PNeZXAXJd/YvfJehUPWaxYSg2V4IyyUjyXDplj7/5XY0UwCARVf9scvhssKj5jXFAusoyUyBaGKmmKMxoi1co7HWmK2hj0YB9pUhIRZmAcIP0CY3bnSRUlNc94Jy2w2hBzDH/bE7AcOXQoGFoj2+OkIIFYdlbFbeO2KoSnyUap1XAhfXpNZhhLPIfRUyHWojeRF0JHC6C81h4oOEHZynGIxjZIinnd+YYzZgBUUhDLqe6jrDCsQgLRTTggMVL04F+rm+8sKx5uPyKpReQdf8fojXO5QjkxhLhbAWqv9VwhskXv11ibObLYRJIpR1tqqFL2e+to7QGcJ2HFaDfFzGDAYVkEcD8Zx2y8X/YLYQBLYaTQYN3EGJOdgrhgt4Y3sPO7DqoLJaemsoqB1SnTI+kKX4MMfW1sgjXYCAs+nRogc7wbJwoWlbpGWIGmT806afFOqT4a9+ZiWUm0YDNbMwrzBtWn6UABpq1gESjxYp5vdL3hbFUb2Q=
  app: obscure-mountain-57946
  on:
    repo: luigomez11/node-shopping-list-integration-tests
